export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Date_lisson} from './Date_lisson/Date_lisson'
export {default as Dash} from './Dash/Dash'
export {default as Login} from './Login/Login'
export {default as Questions} from './Questions/Questions'