export {default as Navbar} from './Navbar/Navbar'
export {default as Header} from './Header/Header'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'
export {default as About_header} from './About_header/About_header'